version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: "dtekportal"
            POSTGRES_PASSWORD: "$DB_PASSWORD"
        volumes:
            # Makes database data persist even if we restart/rebuild container
            - ./db:/var/lib/postgresql/data
    web:
        build: .
        env_file: variables.env
        ports:
            - "$EXPOSE_PORT:8000"
        depends_on:
            - db
        volumes:
            - ./locale:/locale
            - ./logs:/logs
            - ./scripts:/scripts
