version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: dtekportal
    web:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
