version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: dtekportal
        volumes:
            # Makes database data persist even if we restart/rebuild container
            - ./db:/var/lib/postgresql/data
    web:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - ./locale:/locale
            - ./logs:/logs
            - ./scripts:/scripts
